### PR TITLE
prop spawn and diving timer

### PR DESCRIPTION
**Pull request by Sanriku-Gaming**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

Updated the config to add a few zones as well as a quick debug option. 
Added a prop spawn function in client for the box zones being created so they can be targetable with qb-target. 
Added a timer while diving to show remaining time in the tank (QoL).
Rewrote the sell function to account for percentages based on the total being sold.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) Yes. It's been running in my server for a week with no reported issue.
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes

### CODE REVIEW

**Review by IdrisDose — APPROVED** [review]

**Comment by nzkfc** [comment]
@Sanriku-Gaming so we popped your version into production for 2 nights, it works very well.

There is one issues I can't wokr out though, before the update if we got a tank off a shop and we added oxygen to the item info section like this:

```lua
        [1] = {
            name = "diving_gear",
            price = 2500,
            amount = 100,
            info = { oxygen = 1200 },
            type = "item",
            slot = 1,
        },```
        
       It would work fine, lasted ages. Now since the update with your PR, if you buy a diving_gear from the shop, you almost die instantly under the water.
       
       If I spawn in a diving_gear, then it seems to work fine.
       
       Not sure if anything is changed with RegisterNetEvent('qb-diving:server:GiveBackGear', function(oxygen)?

**Comment by Sanriku-Gaming** [comment]
That might be in the callback where it's trying to get the oxygen amount
and set the time remaining underwater to that amount?
`SetPedMaxTimeUnderwater(ped, oxygen)`
I don't set the info in the shop, so that the 'nil' check catches it in the
removegear function on first use. I had 1 person report a similar thing
with a tank, so maybe it's catching 'nil' too quickly and setting the time
remaining to that?

**Comment by nzkfc** [comment]
Figured it out,  I set you set the tank time already so the shop item info
was conflicting. Might be best to update tank time to a config?

**Comment by Sanriku-Gaming** [comment]
> 

So, I tried to make it a config item but it kept having issues with the number/float. I really couldn't figure out why, but it was working when set in the server side, so I left it.

**Pull request closed without merging**
