### PR TITLE
rewrite diving gear code

### PR DESCRIPTION
**Pull request by evanillaa**

### CODE REVIEW

**Comment by ARSSANTO** [comment]
conflict

**Comment by evanillaa** [comment]
> conflict

Why ?

**Comment by ARSSANTO** [comment]
when i use diving gear its giving nil value field ?

**Comment by evanillaa** [comment]
@ARSSANTO 
you replace this ?
QBCore.Functions.CreateUseableItem("diving_gear", function(source, item)
	local Player = QBCore.Functions.GetPlayer(source)
	if Player.Functions.GetItemBySlot(item.slot) ~= nil then
        TriggerClientEvent('qb-diving:client:UseGear', source, item.info.air)
    end
end)

server side ?

**Comment by ARSSANTO** [comment]
yes sir

**Comment by evanillaa** [comment]
download all file
https://github.com/evanillaa/qb-diving/tree/patch-6

its working

**Comment by chunce01** [comment]
Where is the item info for the air level set on the diving gear?

**Comment by izMystic** [comment]
conflicts

**Pull request closed without merging**
