### PR TITLE
Add Brazilian Portuguese translations

### PR DESCRIPTION
**Pull request by ggfto**
Add support for pt-br language.

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? YES
Does your code fit the style guidelines? YES
Does your PR fit the contribution guidelines? YES

### CODE REVIEW

**Comment by r0adra93** [comment]
UPDATE THIS and i will review it!

**Comment by ggfto** [comment]
@r0adra93 updated!

**Review by r0adra93 — APPROVED** [review]
LGTM

**Review by zwkf — APPROVED** [review]
LGTM

**Pull request merged**
