### PR TITLE
Add Coral prop/outline and fix Delete Object

### PR DESCRIPTION
**Pull request by r0adra93**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? [yes

### CODE REVIEW

**Review by KamuiKody — APPROVED** [review]
wrote this for my own server and when i cleaned up my github i cleaned up too much this works well! Ready to ship

**Comment by nzkfc** [comment]
Perfect this works! Tested it on 8 of our diving locations and is great.

**Comment by nzkfc** [comment]
Coral[k] = CreateObject(CoralProp, v.coords.x, v.coords.y, v.coords.z+**0.2**, false, false, false)
        
        Changing this to 0.2 seems to put the coral onto the floor for me everywhere no matter the slope etc.
        
image

https://i.imgur.com/3RTfY29.png

**Review by zwkf — APPROVED** [review]
LGTM

**Pull request closed without merging**
